"""

Revision ID: e343ad807674
Revises: 42aec5ea5c34
Create Date: 2023-02-09 13:34:27.949741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e343ad807674"
down_revision = "42aec5ea5c34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
